name: CI/CD Interactive Calculator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image tags
      id: vars
      run: |
        TAG="v1.0.${{ github.run_number }}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Unit Tests
      run: |
        PYTHONPATH=backend pytest backend/tests

    - name: Run Linter
      run: |
        flake8 backend/app.py

    - name: Build Docker Images
      run: |
        docker build -t frontend-calc:latest ./frontend
        docker build -t backend-calc:latest ./backend

    - name: Run Security Scan (Trivy)
    run: |
        sudo apt-get install wget -y
        wget https://aquasecurity.github.io/trivy-repo/deb/public.key -O- | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y
        trivy --version
        trivy image backend-calc:latest || true

    - name: Simulated Deployment (Dev)
      run: |
        echo "Simulated deployment to Dev environment."

    - name: Simulated Smoke Test
      run: |
        echo "Simulated smoke test after deployment."

    - name: Simulated Slack Notification
      run: |
        echo "Simulated sending Slack notification."
